#!/usr/bin/env node

const fs = require('fs-extra');
const path = require('path');
const toml = require('smol-toml');
const postcss = require('postcss');
const selectorParser = require('postcss-selector-parser');
const crypto = require('crypto');
const { parse } = require('node-html-parser');
const browserSync = require('browser-sync').create();

const SRC_DIR = './pages';
const LAYOUT_DIR = './layout';
const DIST_DIR = './dist';
const CSS_DIST_DIR = path.join(DIST_DIR, 'css');

let classMap = {};

// --- ユーティリティ ---
function getHash(name) {
    if (!classMap[name]) {
        const hash = crypto.createHash('md5').update(name).digest('hex').slice(0, 8);
        classMap[name] = `c_${hash}`;
    }
    return classMap[name];
}

const hashPlugin = postcss.plugin('postcss-hash-classes', () => {
    return (root) => {
        root.walkRules(rule => {
            rule.selector = selectorParser(selectors => {
                selectors.walkClasses(classNode => {
                    classNode.value = getHash(classNode.value);
                });
            }).processSync(rule.selector);
        });
    };
});

function hashHtmlClasses(htmlString) {
    const root = parse(htmlString);
    root.querySelectorAll('[class]').forEach(el => {
        const classes = el.getAttribute('class').split(/\s+/).filter(Boolean);
        el.setAttribute('class', classes.map(getHash).join(' '));
    });
    return root.toString();
}

// --- コマンド: Init ---
async function init() {
    console.log('Initializing mssgen project...');
    await fs.ensureDir(SRC_DIR);
    await fs.ensureDir(LAYOUT_DIR);

    const configContent = `title = "My MSSGen Site"\ndescription = "Generated by mssgen"\nyear = 2026`;
    await fs.writeFile('./config.toml', configContent);

    await fs.writeFile(path.join(LAYOUT_DIR, 'global.css'), 'body { font-family: sans-serif; background: #fafafa; padding: 20px; }');
    await fs.writeFile(path.join(LAYOUT_DIR, 'header.html'), '<header class="header"><h1>{{title}}</h1></header>');
    await fs.writeFile(path.join(LAYOUT_DIR, 'header.css'), '.header { border-bottom: 2px solid #333; }');
    await fs.writeFile(path.join(LAYOUT_DIR, 'footer.html'), '<footer class="footer"><p>&copy; {{year}}</p></footer>');
    await fs.writeFile(path.join(LAYOUT_DIR, 'footer.css'), '.footer { margin-top: 20px; color: #666; }');
    await fs.writeFile(path.join(SRC_DIR, 'index.html'), '<head><meta charset="UTF-8"><title>{{title}}</title></head><body><main><h2>Home</h2><p>{{description}}</p></main></body>');

    console.log('Done! Run "npx mssgen serve" to start dev server.');
}

// --- コマンド: Build ---
async function build() {
    classMap = {}; // ハッシュマップをリセット
    if (!fs.existsSync('./config.toml')) {
        console.error('Error: config.toml not found.');
        process.exit(1);
    }

    const CONFIG = toml.parse(await fs.readFile('./config.toml', 'utf-8'));
    await fs.emptyDir(DIST_DIR);
    await fs.ensureDir(CSS_DIST_DIR);

    if (await fs.pathExists(path.join(LAYOUT_DIR, 'global.css'))) {
        await fs.copy(path.join(LAYOUT_DIR, 'global.css'), path.join(CSS_DIST_DIR, 'global.css'));
    }

    const processPart = async (name) => {
        const hPath = path.join(LAYOUT_DIR, `${name}.html`);
        const cPath = path.join(LAYOUT_DIR, `${name}.css`);
        if (!fs.existsSync(hPath) || !fs.existsSync(cPath)) return '';
        const html = await fs.readFile(hPath, 'utf-8');
        const css = await fs.readFile(cPath, 'utf-8');
        const processedCss = await postcss([hashPlugin]).process(css, { from: undefined });
        await fs.writeFile(path.join(CSS_DIST_DIR, `${name}.css`), processedCss.css);
        return hashHtmlClasses(html);
    };

    const headerHtml = await processPart('header');
    const footerHtml = await processPart('footer');

    const files = await fs.readdir(SRC_DIR, { recursive: true });
    for (const file of files) {
        const sPath = path.join(SRC_DIR, file);
        const dPath = path.join(DIST_DIR, file);
        if ((await fs.stat(sPath)).isDirectory()) {
            await fs.ensureDir(dPath);
            continue;
        }

        if (path.extname(file) === '.html') {
            let body = await fs.readFile(sPath, 'utf-8');
            let full = headerHtml + body + footerHtml;
            for (const [k, v] of Object.entries(CONFIG)) {
                full = full.replace(new RegExp(`{{${k}}}`, 'g'), v);
            }
            const links = `\n<link rel="stylesheet" href="/css/global.css">\n<link rel="stylesheet" href="/css/header.css">\n<link rel="stylesheet" href="/css/footer.css">`;
            full = full.replace('</head>', `${links}\n</head>`);
            await fs.writeFile(dPath, full);
        } else {
            await fs.copy(sPath, dPath);
        }
    }
    console.log(`[${new Date().toLocaleTimeString()}] Build completed.`);
}

// --- コマンド: Serve (Watch & Dev Server) ---
function serve() {
    browserSync.init({
        server: DIST_DIR,
        files: [DIST_DIR], // dist内の変更を監視してリロード
        open: true,
        notify: false
    });

    // ソースファイルの変更を監視して再ビルド
    const watcher = fs.watch('.', { recursive: true }, async (eventType, filename) => {
        if (filename && !filename.startsWith('dist') && !filename.startsWith('.git') && !filename.startsWith('node_modules')) {
            await build();
            browserSync.reload();
        }
    });
}

// --- メイン処理 ---
const args = process.argv.slice(2);
if (args[0] === 'init') {
    init();
} else if (args[0] === 'serve') {
    build().then(serve);
} else {
    build().catch(console.error);
}