const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { URL } = require('node:url');
const DIST_DIR_NAME = 'dist';
const CACHE_DIR_NAME = '.mssgen-cache';
const COMMON_DIR_NAME = 'common';
const SETTINGS_FILE_NAME = 'setting.json';
const DEV_SERVER_PORT = Number(process.env.MSSGEN_PORT || 3000);
const LIVE_RELOAD_ENDPOINT = '/__mssgen/livereload';
const WATCH_DEBOUNCE_MS = 50;
const WATCH_POLL_INTERVAL_MS = 250;
const WEBP_SOURCE_EXTENSIONS = new Set(['.png', '.jpg', '.jpeg']);
const LIVE_RELOAD_SNIPPET = `<script>
(() => {
  const source = new EventSource('${LIVE_RELOAD_ENDPOINT}');
  source.addEventListener('reload', () => window.location.reload());
  source.onerror = () => {
    source.close();
    setTimeout(() => window.location.reload(), 1000);
  };
})();
</script>`;
const BINARY_EXTENSIONS = new Set([
  '.7z', '.avif', '.bmp', '.bz2', '.class', '.doc', '.docx', '.eot', '.exe', '.gif', '.gz',
  '.ico', '.jar', '.jpeg', '.jpg', '.mov', '.mp3', '.mp4', '.pdf', '.png', '.ppt', '.pptx',
  '.rar', '.tar', '.tgz', '.ttf', '.wav', '.webm', '.webp', '.woff', '.woff2', '.xls', '.xlsx',
  '.zip',
]);
const ROOT_IGNORE_NAMES = new Set([
  DIST_DIR_NAME,
  CACHE_DIR_NAME,
  'node_modules',
  '.git',
  'package.json',
  'package-lock.json',
]);
const BUILD_IGNORE_NAMES = new Set([
  COMMON_DIR_NAME,
  SETTINGS_FILE_NAME,
]);
const MIME_TYPES = {
  '.css': 'text/css; charset=utf-8',
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.txt': 'text/plain; charset=utf-8',
  '.webp': 'image/webp',
  '.xml': 'application/xml; charset=utf-8',
};
const NAMED_BLOCK_REFERENCE_PATTERN = /\{\{\{\{([\s\S]*?)\}\}\}\}/g;

const INIT_FILES = {
  [SETTINGS_FILE_NAME]: '{\n  "SITE_NAME": "My Site",\n  "SITE_DESCRIPTION": "Generated by mssgen"\n}\n',
  [path.join(COMMON_DIR_NAME, 'header.html')]: '<header>\n  <h1>{SITE_NAME}</h1>\n  <p>{SITE_DESCRIPTION}</p>\n</header>\n',
  [path.join(COMMON_DIR_NAME, 'footer.html')]: '<footer>\n  <small>&copy; {SITE_NAME}</small>\n</footer>\n',
  'index.html': '<!DOCTYPE html>\n<html lang="ja">\n  <body>\n    {{header.html}}\n    <main>\n      <h2>Welcome to mssgen</h2>\n      <p>トップページを編集してください。</p>\n    </main>\n    {{footer.html}}\n  </body>\n</html>\n',
};

function warn(message) {
  console.warn(`[mssgen] ${message}`);
}

function info(message) {
  console.log(`[mssgen] ${message}`);
}

function ensureDir(dirPath) {
  fs.mkdirSync(dirPath, { recursive: true });
}

function getSharp() {
  if (globalThis.__MSSGEN_TEST_SHARP__) {
    return globalThis.__MSSGEN_TEST_SHARP__;
  }

  return require('sharp');
}

function writeFileIfMissing(filePath, contents) {
  if (fs.existsSync(filePath)) {
    return false;
  }

  ensureDir(path.dirname(filePath));
  fs.writeFileSync(filePath, contents, 'utf8');
  return true;
}

function init(rootDir = process.cwd()) {
  const createdPaths = [];

  for (const [relativePath, contents] of Object.entries(INIT_FILES)) {
    const absolutePath = path.join(rootDir, relativePath);
    if (writeFileIfMissing(absolutePath, contents)) {
      createdPaths.push(relativePath.split(path.sep).join('/'));
    }
  }

  if (createdPaths.length === 0) {
    info('初期化は不要です。必要なファイルはすでに存在します。');
    return createdPaths;
  }

  createdPaths.forEach((relativePath) => info(`created: ${relativePath}`));
  info(`init complete: ${createdPaths.length} file(s)`);
  return createdPaths;
}

function loadSettings(rootDir) {
  const settingsPath = path.join(rootDir, SETTINGS_FILE_NAME);

  if (!fs.existsSync(settingsPath)) {
    warn('setting.json が見つからないため、変数置換をスキップします。');
    return {};
  }

  try {
    const raw = fs.readFileSync(settingsPath, 'utf8');
    const parsed = JSON.parse(raw);

    if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
      warn('setting.json はオブジェクト形式である必要があります。');
      return {};
    }

    return parsed;
  } catch (error) {
    warn(`setting.json の読み込みに失敗しました: ${error.message}`);
    return {};
  }
}

function listFilesRecursively(dirPath, baseDir = dirPath) {
  if (!fs.existsSync(dirPath)) {
    return [];
  }

  return fs.readdirSync(dirPath, { withFileTypes: true }).flatMap((entry) => {
    const absolutePath = path.join(dirPath, entry.name);

    if (entry.isDirectory()) {
      return listFilesRecursively(absolutePath, baseDir);
    }

    if (!entry.isFile()) {
      return [];
    }

    return [{
      absolutePath,
      relativePath: path.relative(baseDir, absolutePath),
    }];
  });
}

function parseNamedBlockDefinitions(content) {
  const namedBlocks = [];
  const segments = [];
  let cursor = 0;
  let index = 0;

  while (index < content.length) {
    const openIndex = content.indexOf('{{{', index);
    if (openIndex === -1) {
      break;
    }

    if (content.startsWith('{{{{', openIndex)) {
      index = openIndex + 4;
      continue;
    }

    const namePrefixIndex = openIndex + 3;
    const separatorIndex = content.indexOf(';', namePrefixIndex);
    if (separatorIndex === -1) {
      index = openIndex + 3;
      continue;
    }

    const header = content.slice(namePrefixIndex, separatorIndex).trim();
    if (!header.startsWith('name:')) {
      index = openIndex + 3;
      continue;
    }

    const key = header.slice('name:'.length).trim();
    let closeIndex = separatorIndex + 1;
    while (true) {
      closeIndex = content.indexOf('}}}', closeIndex);
      if (closeIndex === -1) {
        break;
      }

      if (content[closeIndex + 3] !== '}') {
        break;
      }

      closeIndex += 4;
    }

    if (closeIndex === -1) {
      index = openIndex + 3;
      continue;
    }

    segments.push(content.slice(cursor, openIndex));
    namedBlocks.push({
      key,
      content: content.slice(separatorIndex + 1, closeIndex),
    });
    cursor = closeIndex + 3;
    index = cursor;
  }

  segments.push(content.slice(cursor));

  return {
    contentWithoutDefinitions: segments.join(''),
    namedBlocks,
  };
}

function collectNamedBlocksFromContent(content) {
  return parseNamedBlockDefinitions(content).namedBlocks;
}

function stripNamedBlockDefinitions(content) {
  return parseNamedBlockDefinitions(content).contentWithoutDefinitions;
}

function replaceNamedBlockReferences(content, resolvedNamedBlocks) {
  return content.replace(NAMED_BLOCK_REFERENCE_PATTERN, (_, name) => {
    const key = String(name).trim();

    if (!(key in resolvedNamedBlocks)) {
      warn(`name ブロック '${key}' が見つかりません。`);
      return '';
    }

    return resolvedNamedBlocks[key];
  });
}

function resolveNamedBlocks(namedBlocks) {
  const resolvedNamedBlocks = {};
  const resolutionState = new Map();

  function resolveBlock(key) {
    if (!(key in namedBlocks)) {
      warn(`name ブロック '${key}' が見つかりません。`);
      return '';
    }

    if (resolutionState.get(key) === 'done') {
      return resolvedNamedBlocks[key];
    }

    if (resolutionState.get(key) === 'resolving') {
      warn(`name ブロック '${key}' の再帰参照を検出したため展開を停止しました。`);
      return '';
    }

    resolutionState.set(key, 'resolving');
    const parsed = parseNamedBlockDefinitions(namedBlocks[key]);
    const resolvedContent = parsed.contentWithoutDefinitions.replace(NAMED_BLOCK_REFERENCE_PATTERN, (_, name) => {
      const referencedKey = String(name).trim();
      return resolveBlock(referencedKey);
    });
    resolutionState.set(key, 'done');
    resolvedNamedBlocks[key] = resolvedContent;
    return resolvedContent;
  }

  Object.keys(namedBlocks).forEach((key) => {
    resolveBlock(key);
  });

  return resolvedNamedBlocks;
}

function loadNamedBlocks(rootDir) {
  const namedBlocks = {};

  for (const file of getWatchedFiles(rootDir)) {
    if (!isTextFile(file.relativePath)) {
      continue;
    }

    const source = fs.readFileSync(file.absolutePath, 'utf8');
    const parsed = parseNamedBlockDefinitions(source);
    for (const { key, content } of parsed.namedBlocks) {
      if (!key) {
        warn(`無名の name ブロックを検出したため無視しました (${toPosixPath(file.relativePath)})。`);
        continue;
      }

      if (key in namedBlocks) {
        warn(`name ブロック '${key}' が重複したため、後から見つかった定義 (${toPosixPath(file.relativePath)}) を無視しました。`);
        continue;
      }

      namedBlocks[key] = content;
    }
  }

  return resolveNamedBlocks(namedBlocks);
}

function injectResolvedNamedBlocks(content, resolvedNamedBlocks) {
  const parsed = parseNamedBlockDefinitions(content);
  return replaceNamedBlockReferences(parsed.contentWithoutDefinitions, resolvedNamedBlocks);
}

function injectNamedBlocks(content, namedBlocks) {
  return injectResolvedNamedBlocks(content, resolveNamedBlocks(namedBlocks));
}

function loadParts(rootDir) {
  const partsDir = path.join(rootDir, COMMON_DIR_NAME);

  if (!fs.existsSync(partsDir)) {
    return {};
  }

  return listFilesRecursively(partsDir, partsDir).reduce((parts, file) => {
    parts[file.relativePath] = fs.readFileSync(file.absolutePath, 'utf8');
    return parts;
  }, {});
}

const PART_REFERENCE_PATTERN = /(?<!\{)\{\{(?!\{)(.*?)\}\}(?!\})/g;

function injectParts(content, parts, stack = []) {
  return content.replace(PART_REFERENCE_PATTERN, (_, name) => {
    const key = String(name).trim();

    if (!(key in parts)) {
      warn(`パーツ '${key}' が見つかりません。`);
      return '';
    }

    if (stack.includes(key)) {
      warn(`パーツ '${key}' の再帰参照を検出したため展開を停止しました。`);
      return '';
    }

    return injectParts(parts[key], parts, [...stack, key]);
  });
}

function injectSettings(content, settings) {
  return content.replace(/{(.*?)}/g, (match, name) => {
    const key = String(name).trim();

    if (!(key in settings)) {
      return match;
    }

    return String(settings[key]);
  });
}

function toPosixPath(filePath) {
  return filePath.split(path.sep).join('/');
}

function getTopLevelName(relativePath) {
  return toPosixPath(relativePath).split('/')[0];
}

function shouldIgnoreRelativePath(relativePath) {
  return ROOT_IGNORE_NAMES.has(getTopLevelName(relativePath));
}

function shouldBuildRelativePath(relativePath) {
  return !BUILD_IGNORE_NAMES.has(getTopLevelName(relativePath));
}

function isTextFile(relativePath) {
  return !BINARY_EXTENSIONS.has(path.extname(relativePath).toLowerCase());
}

function shouldConvertImageToWebp(relativePath) {
  return WEBP_SOURCE_EXTENSIONS.has(path.extname(relativePath).toLowerCase());
}

function getWebpRelativePath(relativePath) {
  const normalizedPath = toPosixPath(relativePath);
  return normalizedPath.replace(/\.(png|jpe?g)$/i, '.webp');
}

function getBuildOutputRelativePath(relativePath) {
  return shouldConvertImageToWebp(relativePath)
    ? getWebpRelativePath(relativePath)
    : toPosixPath(relativePath);
}

function getWatchedFiles(rootDir) {
  return listFilesRecursively(rootDir, rootDir)
    .filter((file) => !shouldIgnoreRelativePath(file.relativePath));
}

function getSourceFiles(rootDir, outputDir = path.join(rootDir, DIST_DIR_NAME)) {
  return getWatchedFiles(rootDir)
    .filter((file) => shouldBuildRelativePath(file.relativePath))
    .map((file) => ({
      ...file,
      relativePath: toPosixPath(file.relativePath),
      outputPath: path.join(outputDir, getBuildOutputRelativePath(file.relativePath)),
    }));
}

function emptyDir(dirPath) {
  fs.rmSync(dirPath, { recursive: true, force: true });
  ensureDir(dirPath);
}

function getCacheDir(rootDir) {
  return path.join(rootDir, CACHE_DIR_NAME);
}

function getAssetCacheManifestPath(rootDir) {
  return path.join(getCacheDir(rootDir), 'assets.json');
}

function getCachedOutputPath(rootDir, outputRelativePath) {
  return path.join(getCacheDir(rootDir), 'outputs', outputRelativePath);
}

function makeTempBuildDir(rootDir) {
  return path.join(rootDir, `${DIST_DIR_NAME}.__mssgen_tmp_${process.pid}_${Date.now()}`);
}

function replaceDir(targetDir, nextDir) {
  const backupDir = `${targetDir}.__mssgen_old_${process.pid}_${Date.now()}`;

  if (fs.existsSync(targetDir)) {
    fs.renameSync(targetDir, backupDir);
  }

  try {
    fs.renameSync(nextDir, targetDir);
  } catch (error) {
    if (fs.existsSync(backupDir) && !fs.existsSync(targetDir)) {
      fs.renameSync(backupDir, targetDir);
    }
    throw error;
  }

  fs.rmSync(backupDir, { recursive: true, force: true });
}

function createConvertedAssetMap(sourceFiles) {
  return new Map(
    sourceFiles
      .filter((file) => shouldConvertImageToWebp(file.relativePath))
      .map((file) => [file.relativePath, getWebpRelativePath(file.relativePath)]),
  );
}

function splitResourceSuffix(resourcePath) {
  const match = resourcePath.match(/[?#].*$/);
  if (!match) {
    return { pathname: resourcePath, suffix: '' };
  }

  return {
    pathname: resourcePath.slice(0, match.index),
    suffix: match[0],
  };
}

function resolveAssetReferencePath(currentRelativePath, resourcePath) {
  if (!resourcePath || /^(?:[a-z]+:)?\/\//i.test(resourcePath) || resourcePath.startsWith('data:')) {
    return null;
  }

  const currentDir = path.posix.dirname(toPosixPath(currentRelativePath));
  const normalizedPath = resourcePath.startsWith('/')
    ? path.posix.normalize(resourcePath.slice(1))
    : path.posix.normalize(path.posix.join(currentDir === '.' ? '' : currentDir, resourcePath));

  if (normalizedPath.startsWith('..')) {
    return null;
  }

  return normalizedPath;
}

function formatAssetReferencePath(currentRelativePath, originalPathname, targetRelativePath) {
  if (originalPathname.startsWith('/')) {
    return `/${targetRelativePath}`;
  }

  const currentDir = path.posix.dirname(toPosixPath(currentRelativePath));
  const relativePath = path.posix.relative(currentDir === '.' ? '' : currentDir, targetRelativePath);
  return relativePath || path.posix.basename(targetRelativePath);
}

function rewriteAssetReferences(content, currentRelativePath, convertedAssetMap) {
  return content.replace(/[^^\s"'`()<>]+\.(?:png|jpe?g)(?:[?#][^\s"'`()<>]*)?/gi, (match) => {
    const { pathname, suffix } = splitResourceSuffix(match);
    const resolvedPath = resolveAssetReferencePath(currentRelativePath, pathname);

    if (!resolvedPath || !convertedAssetMap.has(resolvedPath)) {
      return match;
    }

    const convertedPath = convertedAssetMap.get(resolvedPath);
    return `${formatAssetReferencePath(currentRelativePath, pathname, convertedPath)}${suffix}`;
  });
}

function injectBuiltByComment(html) {
  const comment = '<!-- built by mssgen -->';

  if (html.includes(comment)) {
    return html;
  }

  if (html.includes('</body>')) {
    return html.replace('</body>', `${comment}\n</body>`);
  }

  return `${html}\n${comment}`;
}

async function convertImageToWebp(sourcePath, outputPath) {
  const sharp = getSharp();
  await sharp(sourcePath)
    .webp({ quality: 82 })
    .toFile(outputPath);
}

function loadAssetCache(rootDir) {
  const manifestPath = getAssetCacheManifestPath(rootDir);

  if (!fs.existsSync(manifestPath)) {
    return {};
  }

  try {
    const raw = fs.readFileSync(manifestPath, 'utf8');
    const parsed = JSON.parse(raw);
    return parsed && typeof parsed === 'object' && !Array.isArray(parsed) ? parsed : {};
  } catch (error) {
    warn(`asset cache の読み込みに失敗しました: ${error.message}`);
    return {};
  }
}

function saveAssetCache(rootDir, assetCache) {
  const manifestPath = getAssetCacheManifestPath(rootDir);
  ensureDir(path.dirname(manifestPath));
  fs.writeFileSync(manifestPath, `${JSON.stringify(assetCache, null, 2)}\n`, 'utf8');
}

function restoreCachedAsset(rootDir, relativePath, outputPath, assetCache) {
  const cacheEntry = assetCache[relativePath];
  const outputRelativePath = getBuildOutputRelativePath(relativePath);
  const cachedOutputPath = getCachedOutputPath(rootDir, outputRelativePath);

  if (!cacheEntry || cacheEntry.outputRelativePath !== outputRelativePath || !fs.existsSync(cachedOutputPath)) {
    return false;
  }

  const sourceStat = fs.statSync(path.join(rootDir, relativePath));
  if (cacheEntry.mtimeMs !== sourceStat.mtimeMs) {
    return false;
  }

  ensureDir(path.dirname(outputPath));
  fs.copyFileSync(cachedOutputPath, outputPath);
  return true;
}

function updateAssetCacheEntry(rootDir, relativePath, outputPath, assetCache) {
  const sourceStat = fs.statSync(path.join(rootDir, relativePath));
  const outputRelativePath = getBuildOutputRelativePath(relativePath);
  const cachedOutputPath = getCachedOutputPath(rootDir, outputRelativePath);

  ensureDir(path.dirname(cachedOutputPath));
  fs.copyFileSync(outputPath, cachedOutputPath);
  assetCache[relativePath] = {
    mtimeMs: sourceStat.mtimeMs,
    outputRelativePath,
  };
}

function resolvePartContents(parts, namedBlocks) {
  return Object.fromEntries(
    Object.entries(parts).map(([key, content]) => [key, injectResolvedNamedBlocks(content, namedBlocks)]),
  );
}

async function build(rootDir = process.cwd()) {
  const distDir = path.join(rootDir, DIST_DIR_NAME);
  const tempDistDir = makeTempBuildDir(rootDir);
  emptyDir(tempDistDir);

  const settings = loadSettings(rootDir);
  const namedBlocks = loadNamedBlocks(rootDir);
  const parts = resolvePartContents(loadParts(rootDir), namedBlocks);
  const sourceFiles = getSourceFiles(rootDir, tempDistDir);
  const convertedAssetMap = createConvertedAssetMap(sourceFiles);
  const assetCache = loadAssetCache(rootDir);

  try {
    for (const { absolutePath, outputPath, relativePath } of sourceFiles) {
      ensureDir(path.dirname(outputPath));

      if (isTextFile(relativePath)) {
        const source = fs.readFileSync(absolutePath, 'utf8');
        const withNamedBlocks = injectResolvedNamedBlocks(source, namedBlocks);
        const withParts = injectParts(withNamedBlocks, parts);
        const withSettings = injectSettings(withParts, settings);
        const withAssetReferences = rewriteAssetReferences(withSettings, relativePath, convertedAssetMap);
        const result = path.extname(relativePath).toLowerCase() === '.html'
          ? injectBuiltByComment(withAssetReferences)
          : withAssetReferences;
        fs.writeFileSync(outputPath, result, 'utf8');
      } else if (shouldConvertImageToWebp(relativePath)) {
        if (restoreCachedAsset(rootDir, relativePath, outputPath, assetCache)) {
          info(`cached: ${relativePath}`);
          continue;
        }

        await convertImageToWebp(absolutePath, outputPath);
        updateAssetCacheEntry(rootDir, relativePath, outputPath, assetCache);
      } else {
        fs.copyFileSync(absolutePath, outputPath);
      }

      info(`built: ${relativePath}`);
    }

    replaceDir(distDir, tempDistDir);
    saveAssetCache(rootDir, assetCache);
  } catch (error) {
    fs.rmSync(tempDistDir, { recursive: true, force: true });
    throw error;
  }

  info(`build complete: ${sourceFiles.length} file(s)`);
  return sourceFiles.length;
}

function createWatcherSnapshot(rootDir) {
  return new Map(
    getWatchedFiles(rootDir).map((file) => [
      toPosixPath(file.relativePath),
      fs.statSync(file.absolutePath).mtimeMs,
    ]),
  );
}

function diffWatcherSnapshots(previousSnapshot, nextSnapshot) {
  const changes = [];

  for (const [relativePath, nextMtimeMs] of nextSnapshot) {
    if (!previousSnapshot.has(relativePath)) {
      changes.push({ eventName: 'add', relativePath });
      continue;
    }

    if (previousSnapshot.get(relativePath) !== nextMtimeMs) {
      changes.push({ eventName: 'change', relativePath });
    }
  }

  for (const relativePath of previousSnapshot.keys()) {
    if (!nextSnapshot.has(relativePath)) {
      changes.push({ eventName: 'unlink', relativePath });
    }
  }

  return changes.sort((left, right) => left.relativePath.localeCompare(right.relativePath));
}

function createWatcher(rootDir) {
  let currentSnapshot = createWatcherSnapshot(rootDir);
  let closed = false;
  let pendingChanges = [];
  let debounceTimer = null;
  let pollingTimer = null;
  const listeners = new Map();

  const emit = (eventName, ...args) => {
    const handlers = listeners.get(eventName) || [];
    for (const handler of handlers) {
      handler(...args);
    }
  };

  const flushPendingChanges = () => {
    debounceTimer = null;
    const changes = pendingChanges;
    pendingChanges = [];

    const normalizedChanges = changes.map((change) => ({
      ...change,
      filePath: path.join(rootDir, change.relativePath),
    }));

    for (const change of normalizedChanges) {
      emit(change.eventName, change.filePath);
      emit('all', change.eventName, change.filePath);
    }

    emit('batch', normalizedChanges);
  };

  const scheduleFlush = () => {
    if (debounceTimer) {
      clearTimeout(debounceTimer);
    }

    debounceTimer = setTimeout(flushPendingChanges, WATCH_DEBOUNCE_MS);
  };

  const poll = () => {
    if (closed) {
      return;
    }

    try {
      const nextSnapshot = createWatcherSnapshot(rootDir);
      const changes = diffWatcherSnapshots(currentSnapshot, nextSnapshot);

      if (changes.length > 0) {
        currentSnapshot = nextSnapshot;
        pendingChanges.push(...changes);
        scheduleFlush();
      }
    } catch (error) {
      warn(`watch error: ${error.message}`);
    }
  };

  pollingTimer = setInterval(poll, WATCH_POLL_INTERVAL_MS);
  if (typeof pollingTimer.unref === 'function') {
    pollingTimer.unref();
  }

  return {
    close() {
      closed = true;
      if (pollingTimer) {
        clearInterval(pollingTimer);
      }
      if (debounceTimer) {
        clearTimeout(debounceTimer);
      }
    },
    on(eventName, handler) {
      const handlers = listeners.get(eventName) || [];
      handlers.push(handler);
      listeners.set(eventName, handlers);
      return this;
    },
  };
}

function getContentType(filePath) {
  return MIME_TYPES[path.extname(filePath).toLowerCase()] || 'application/octet-stream';
}

function injectLiveReloadSnippet(html) {
  if (html.includes(LIVE_RELOAD_ENDPOINT)) {
    return html;
  }

  if (html.includes('</body>')) {
    return html.replace('</body>', `${LIVE_RELOAD_SNIPPET}\n</body>`);
  }

  return `${html}\n${LIVE_RELOAD_SNIPPET}`;
}

function createLiveReloadFallbackHtml(requestUrl) {
  const escapedRequestUrl = String(requestUrl)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

  return injectLiveReloadSnippet(`<!DOCTYPE html>\n<html lang="ja">\n  <head>\n    <meta charset="utf-8">\n    <meta name="viewport" content="width=device-width, initial-scale=1">\n    <title>Rebuilding...</title>\n  </head>\n  <body>\n    <main>\n      <h1>Rebuilding...</h1>\n      <p>\`${escapedRequestUrl}\` はまだ生成されていません。ビルド完了後に自動で再読み込みします。</p>\n    </main>\n  </body>\n</html>`);
}

function resolveRequestPath(rootDir, requestUrl) {
  const distDir = path.join(rootDir, DIST_DIR_NAME);
  const url = new URL(requestUrl, 'http://127.0.0.1');
  const pathname = decodeURIComponent(url.pathname);
  const safePath = path.normalize(pathname).replace(/^([.][.][/\\])+/, '');
  let filePath = path.join(distDir, safePath);

  if (!filePath.startsWith(distDir)) {
    return null;
  }

  if (fs.existsSync(filePath) && fs.statSync(filePath).isDirectory()) {
    filePath = path.join(filePath, 'index.html');
  }

  if (!path.extname(filePath)) {
    const htmlPath = `${filePath}.html`;

    if (fs.existsSync(htmlPath)) {
      filePath = htmlPath;
    } else {
      filePath = path.join(filePath, 'index.html');
    }
  }

  return filePath;
}

function createDevServer(rootDir, options = {}) {
  const clients = new Set();
  let activeBuildPromise = Promise.resolve(options.waitUntilReady);
  let triggerBuild = typeof options.triggerBuild === 'function' ? options.triggerBuild : null;

  const awaitActiveBuild = () => activeBuildPromise.catch((error) => {
    warn(`build failed while serving request: ${error.message}`);
  });

  const rebuildMissingRequest = async () => {
    if (!triggerBuild) {
      return false;
    }

    try {
      const buildPromise = Promise.resolve(triggerBuild());
      activeBuildPromise = buildPromise;
      await awaitActiveBuild();
      return true;
    } catch (error) {
      warn(`build failed while resolving missing request: ${error.message}`);
      return false;
    }
  };

  const server = http.createServer(async (req, res) => {
    if (!req.url) {
      res.writeHead(400);
      res.end('Bad Request');
      return;
    }

    const url = new URL(req.url, 'http://127.0.0.1');

    if (url.pathname === LIVE_RELOAD_ENDPOINT) {
      res.writeHead(200, {
        'Content-Type': 'text/event-stream; charset=utf-8',
        'Cache-Control': 'no-cache, no-transform',
        Connection: 'keep-alive',
      });
      res.write(': connected\n\n');
      clients.add(res);
      req.on('close', () => clients.delete(res));
      return;
    }

    let filePath = resolveRequestPath(rootDir, req.url);

    if (!filePath || !fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
      await awaitActiveBuild();
      filePath = resolveRequestPath(rootDir, req.url);
    }

    if ((!filePath || !fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) && await rebuildMissingRequest()) {
      filePath = resolveRequestPath(rootDir, req.url);
    }

    if (!filePath || !fs.existsSync(filePath) || !fs.statSync(filePath).isFile()) {
      res.writeHead(404, { 'Content-Type': 'text/html; charset=utf-8' });
      res.end(createLiveReloadFallbackHtml(req.url));
      return;
    }

    const contentType = getContentType(filePath);
    const isHtml = path.extname(filePath).toLowerCase() === '.html';

    if (isHtml) {
      const html = fs.readFileSync(filePath, 'utf8');
      res.writeHead(200, { 'Content-Type': contentType });
      res.end(injectLiveReloadSnippet(html));
      return;
    }

    res.writeHead(200, { 'Content-Type': contentType });
    fs.createReadStream(filePath).pipe(res);
  });

  const broadcastReload = () => {
    for (const client of clients) {
      client.write('event: reload\ndata: now\n\n');
    }
  };

  return {
    server,
    broadcastReload,
    setBuildPromise(buildPromise) {
      activeBuildPromise = Promise.resolve(buildPromise);
    },
  };
}

function dev(rootDir = process.cwd()) {
  let rebuildQueue = Promise.resolve();

  const rebuild = ({ reload = true } = {}) => build(rootDir)
    .then(() => {
      if (reload) {
        broadcastReload();
      }
    })
    .catch((error) => {
      warn(`build failed: ${error.message}`);
    });

  const { server, broadcastReload, setBuildPromise } = createDevServer(rootDir, {
    triggerBuild() {
      rebuildQueue = rebuildQueue.then(() => rebuild({ reload: false }));
      setBuildPromise(rebuildQueue);
      return rebuildQueue;
    },
  });

  rebuildQueue = rebuild();
  setBuildPromise(rebuildQueue);

  server.listen(DEV_SERVER_PORT, () => {
    info(`dev server running at http://127.0.0.1:${DEV_SERVER_PORT}`);
  });

  const watcher = createWatcher(rootDir);

  watcher.on('batch', (changes) => {
    changes.forEach(({ eventName, filePath }) => {
      info(`${eventName}: ${path.relative(rootDir, filePath)}`);
    });

    rebuildQueue = rebuildQueue.then(() => rebuild());
    setBuildPromise(rebuildQueue);
  });

  info('watching for changes...');
  return { watcher, server, rebuildQueue };
}

module.exports = {
  COMMON_DIR_NAME,
  DEV_SERVER_PORT,
  DIST_DIR_NAME,
  INIT_FILES,
  SETTINGS_FILE_NAME,
  LIVE_RELOAD_ENDPOINT,
  MIME_TYPES,
  WATCH_DEBOUNCE_MS,
  WATCH_POLL_INTERVAL_MS,
  build,
  createConvertedAssetMap,
  createDevServer,
  createWatcher,
  createWatcherSnapshot,
  dev,
  diffWatcherSnapshots,
  formatAssetReferencePath,
  getSourceFiles,
  getWebpRelativePath,
  init,
  injectBuiltByComment,
  createLiveReloadFallbackHtml,
  injectLiveReloadSnippet,
  injectNamedBlocks,
  injectParts,
  injectSettings,
  isTextFile,
  listFilesRecursively,
  loadParts,
  loadSettings,
  resolveAssetReferencePath,
  resolveRequestPath,
  rewriteAssetReferences,
  shouldBuildRelativePath,
  shouldConvertImageToWebp,
  shouldIgnoreRelativePath,
  splitResourceSuffix,
  toPosixPath,
  warn,
};
